sudo: false

language: php

php:
  - 5.6
  - 7.0
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
    - php: hhvm-nightly

before_install:
  - composer self-update

before_script:
  - composer install --no-interaction --prefer-source --dev
  - mkdir -p build/logs
